import { claudeSuggest } from '../claude-cli.js';
import {
  readReviews,
  appendReview,
  lastReview,
  summarizeTrend,
  type ReviewScores,
} from '../session/reviewStore.js';
import type { Worker, WorkerCapabilities, WorkerResult } from './types.js';

const SCORES_MARKER = '<!--SCORES-->';

// The self-review is the highest-value, lowest-frequency intelligence call, so it
// runs on the most capable model (Opus) rather than the realtime Sonnet default.
// Override via COPILOT_REVIEW_MODEL if a different id is needed.
import { MODEL_CONFIG } from '../model-config.js';

const REVIEW_MODEL = MODEL_CONFIG.review;

const REVIEW_SYSTEM = `You are a candid but constructive executive coach. You review how ONE person — "You" / "[You]" in the transcript — performed in a meeting they just finished. The other participants are "[Meeting]". Assess the user only; do not critique the others.

IMPORTANT — transcript quality: This transcript is auto-generated by local speech-to-text and is imperfect. Expect misheard or wrong words, dropped or merged words, missing punctuation, run-on segments, and occasional mis-attributed speaker labels ([You] vs [Meeting]). Judge the user on SUBSTANCE — their decisions, reasoning, structure, listening, and how they handled questions — NOT on surface grammar, filler, or awkward phrasing that may be transcription artifacts. When you quote the user, treat the quote as approximate (it may not be verbatim), and never hang a criticism on a single odd word or fragment that is more likely a mis-transcription than something they actually said. If a passage is too garbled to interpret, skip it rather than guess.

Write a tight, specific scorecard in markdown with EXACTLY these sections:

## Self-Review — <meeting title>

**How you showed up:** one or two sentences, honest overall read.

### Strengths
- 2-4 concrete things the user did well, each tied to something specific they said.

### Areas to improve
- 2-4 concrete, actionable improvements. No fluff.

### Question handling
For each question that was directed at the user, quote it briefly and assess their answer:
- **Asked:** "..." — **You:** "<their answer, paraphrased>" — <was it direct/complete/evasive? how to do it better>
If no questions were directed at the user, say so in one line.

### Scores
- **Clarity:** N/5 — <one clause>
- **Decisiveness:** N/5 — <one clause>
- **Concision:** N/5 — <one clause>

### Next-meeting goals
1. <concrete goal>
2. <concrete goal>
3. <optional third>

Then, on the VERY LAST line and nowhere else, emit a machine-readable block:
${SCORES_MARKER}
{"clarity": N, "decisiveness": N, "concision": N, "goals": ["goal 1", "goal 2"]}

Rules: scores are integers 1-5 (1 poor, 5 excellent). The JSON goals must match your "Next-meeting goals" section. Output nothing after the JSON line.`;

export class ReviewWorker implements Worker {
  public readonly name = 'review';
  public readonly capabilities: WorkerCapabilities = {
    network: 'anthropic-only',
    filesystem: { read: [], write: ['~/.meeting-copilot/**'] },
    subprocess: false,
    // Generous safety cap (~15 min): jobs run until done or the user cancels.
    maxDurationMs: 900_000,
    maxMemoryMB: 100,
  };

  async execute(
    params: Record<string, any>,
    signal: AbortSignal,
  ): Promise<WorkerResult> {
    const transcript = params.transcript as string | undefined;
    const title = (params.title as string) || 'Untitled';
    const sessionId = (params.sessionId as string) || '';
    const micWords = Number(params.micWords) || 0;
    const meetingWords = Number(params.meetingWords) || 0;
    const agendaSummary = (params.agendaSummary as string) || '';
    const goals = (params.goals as string) || '';
    const factFlags = Array.isArray(params.factFlags)
      ? (params.factFlags as Array<{ claim: string; verdict: string; correction?: string }>)
      : [];

    if (!transcript || transcript.trim().length < 40) {
      return {
        success: false,
        data: null,
        summary: 'Not enough transcript to review',
        error: 'Transcript too short for a meaningful self-review',
      };
    }

    if (signal.aborted) {
      return { success: false, data: null, summary: 'Review cancelled before start', error: 'Aborted' };
    }

    // ── Derived stats fed to the model alongside the transcript ──
    const totalWords = micWords + meetingWords;
    const talkRatio = totalWords > 0 ? micWords / totalWords : 0;
    const talkPct = Math.round(talkRatio * 100);

    // Cheap heuristic: questions coming from the other side of the table.
    const questionsFromOthers = transcript
      .split('\n')
      .filter((l) => l.startsWith('[Meeting]') && l.includes('?')).length;

    const statsLines = [
      `Talk ratio: you spoke ${talkPct}% of the words (you: ${micWords}, others: ${meetingWords}).`,
      `Questions from others (contain "?"): ${questionsFromOthers}. Identify which were aimed at you and grade your answers.`,
      agendaSummary
        ? `Agenda coverage at meeting end:\n${agendaSummary}`
        : 'Agenda coverage: no agenda was set.',
      factFlags.length > 0
        ? `Fact-check flags against statements you made:\n${factFlags
            .map((f) => `- "${f.claim}" (${f.verdict})${f.correction ? ` — correction: ${f.correction}` : ''}`)
            .join('\n')}`
        : 'Fact-check flags against you: none.',
      goals ? `Your private goals going in:\n${goals}` : 'Your private goals going in: none provided.',
    ].join('\n');

    const userContent = `Meeting: ${title}\n\nDerived stats:\n${statsLines}\n\nFull transcript ("[You]" = the user, "[Meeting]" = others):\n\n${transcript}`;

    try {
      // CLI-only (subscription, no paid API): Opus via claudeSuggest — the review
      // is rare and high-value, so it gets the strongest model (see REVIEW_MODEL).
      const raw = await claudeSuggest(userContent, REVIEW_SYSTEM, signal, undefined, { model: REVIEW_MODEL });

      if (signal.aborted) {
        return { success: false, data: null, summary: 'Review cancelled during execution', error: 'Aborted' };
      }

      const { markdown, scores, parsedGoals } = parseReview(raw);

      // ── Cross-meeting trend: compare against the most recent prior review of
      // a DIFFERENT meeting. Excluding this session's own id prevents a re-run of
      // the latest meeting from comparing it against itself (and inflating the
      // "N prior reviews" count). ──
      const prior = lastReview(sessionId);
      const priorCount = readReviews().filter((r) => r.sessionId !== sessionId).length;
      const trendLine = scores ? summarizeTrend(prior, scores, priorCount) : '';

      // Persist this meeting's record so future reviews can show deltas.
      if (scores) {
        appendReview({
          date: new Date().toISOString(),
          title,
          sessionId,
          scores,
          goals: parsedGoals,
          talkRatio,
        });
      }

      const trendBlock = trendLine
        ? `> **Trend vs last meeting:** ${trendLine}\n\n`
        : prior
          ? ''
          : `> _First tracked meeting — trends will appear after your next review._\n\n`;

      const artifactMarkdown = `${trendBlock}${markdown}`;

      return {
        success: true,
        data: { scores, goals: parsedGoals, talkRatio, trend: trendLine },
        summary: `Self-review ready for: ${title}`,
        artifacts: [
          {
            type: 'markdown',
            content: artifactMarkdown,
            title: `Self-Review — ${title}`,
          },
        ],
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return {
        success: false,
        data: null,
        summary: `Self-review failed: ${message}`,
        error: message,
      };
    }
  }
}

/** Split the model output into display markdown + parsed scores/goals. */
function parseReview(raw: string): {
  markdown: string;
  scores: ReviewScores | null;
  parsedGoals: string[];
} {
  const idx = raw.indexOf(SCORES_MARKER);
  const markdown = (idx >= 0 ? raw.slice(0, idx) : raw).trim();
  const jsonPart = idx >= 0 ? raw.slice(idx + SCORES_MARKER.length) : raw;

  let scores: ReviewScores | null = null;
  let parsedGoals: string[] = [];
  const start = jsonPart.indexOf('{');
  const end = jsonPart.lastIndexOf('}');
  if (start >= 0 && end > start) {
    try {
      const obj = JSON.parse(jsonPart.slice(start, end + 1));
      scores = {
        clarity: clampScore(obj.clarity),
        decisiveness: clampScore(obj.decisiveness),
        concision: clampScore(obj.concision),
      };
      if (Array.isArray(obj.goals)) {
        parsedGoals = obj.goals.map((g: unknown) => String(g)).filter(Boolean).slice(0, 3);
      }
    } catch {
      scores = null;
    }
  }
  return { markdown, scores, parsedGoals };
}

function clampScore(v: unknown): number {
  const n = Math.round(Number(v));
  if (!Number.isFinite(n)) return 3;
  return Math.min(5, Math.max(1, n));
}

export interface ReviewTranscriptRecord {
  source: string; // 'mic' = you, anything else = the other side
  label: string; // e.g. "[You]" / "[Meeting]"
  text: string;
  wordCount?: number;
}

export interface BuildReviewParamsInput {
  transcriptRecords: ReviewTranscriptRecord[];
  title?: string;
  sessionId?: string;
  agendaSummary?: string;
  goals?: string;
  factFlags?: Array<{ claim: string; verdict: string; correction?: string }>;
}

/**
 * Assemble the params `ReviewWorker.execute` expects from raw transcript records
 * + session metadata. Shared by all three entry points so they feed the worker
 * identically: the live stop-path auto-review, the manual in-meeting "Review"
 * Quick Action, and the past-meeting `/present/review` endpoint.
 */
export function buildReviewParams(input: BuildReviewParamsInput): Record<string, any> {
  const { transcriptRecords, title, sessionId, agendaSummary, goals, factFlags } = input;
  const fullTranscript = transcriptRecords.map((r) => `${r.label} ${r.text}`).join('\n');
  let micWords = 0;
  let meetingWords = 0;
  for (const r of transcriptRecords) {
    const w =
      typeof r.wordCount === 'number' && r.wordCount > 0
        ? r.wordCount
        : r.text.trim()
          ? r.text.trim().split(/\s+/).length
          : 0;
    if (r.source === 'mic') micWords += w;
    else meetingWords += w;
  }
  return {
    transcript: fullTranscript,
    title,
    sessionId: sessionId || '',
    micWords,
    meetingWords,
    agendaSummary: agendaSummary || '',
    goals: goals || '',
    factFlags: factFlags || [],
  };
}
